---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-discogssorter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: discogssorter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Release.Name }}
      app.kubernetes.io/component: application
      app.kubernetes.io/name: discogssorter
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: application
        app.kubernetes.io/name: discogssorter
    spec:
      containers:
        - name: {{ .Release.Name }}-discogssorter
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8000
              name: web
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/"
              port: 8000
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: "/"
              port: 8000
              scheme: HTTP