---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-discogssorter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: discogssorter
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: discogssorter
  ports:
    - name: web
      port: 8000
      protocol: TCP