---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bookstack-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
data:
  PUID: {{ .Values.bookstack.puid | quote }}
  PGID: {{ .Values.bookstack.pgid | quote }}
  APP_URL: "https://{{ .Values.global.app_url }}"
  {{- if not .Values.mariadb.host }}
  DB_HOST: "{{ .Release.Name }}-mariadb"
  {{- else }}
  DB_HOST: {{ .Values.mariadb.host | quote }}
  {{- end }}
  DB_USER: {{ .Values.mariadb.user | quote }}
  DB_PASS: {{ .Values.mariadb.pass | quote }}
  DB_DATABASE: {{ .Values.mariadb.name | quote }}
  MAIL_DRIVER: {{ .Values.mail.driver | quote }}
  MAIL_HOST: {{ .Values.mail.host | quote }}
  MAIL_PORT: {{ .Values.mail.port | quote }}
  MAIL_ENCRYPTION: {{ .Values.mail.encryption | quote }}
  MAIL_USERNAME: {{ .Values.mail.username | quote }}
  MAIL_PASSWORD: {{ .Values.mail.password | quote }}
  MAIL_FROM: {{ .Values.mail.from | quote }}
  MAIL_FROM_NAME: {{ .Values.mail.from_name | quote }}
  AZURE_APP_ID: {{ .Values.auth.azure.app_id | quote }}
  AZURE_APP_SECRET: {{ .Values.auth.azure.app_secret | quote }}
  AZURE_TENANT: {{ .Values.auth.azure.tenant | quote }}
  AZURE_AUTO_REGISTER: {{ .Values.auth.azure.auto_register | quote }}
  AZURE_AUTO_CONFIRM_EMAIL: {{ .Values.auth.azure.auto_confirm | quote }}

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-bookstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bookstack.storage.size }}
  storageClassName: {{ .Values.global.storageclass | quote }}


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bookstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Release.Name }}
      app.kubernetes.io/component: application
      app.kubernetes.io/name: bookstack
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: application
        app.kubernetes.io/name: bookstack
    spec:
      containers:
        - name: {{ .Release.Name }}-bookstack
          image: "{{ .Values.bookstack.image.name }}:{{ .Values.bookstack.image.tag }}"
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-bookstack
              mountPath: /config
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-bookstack-env
      volumes:
        - name: {{ .Release.Name }}-bookstack
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-bookstack

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bookstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-bookstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
  annotations:
    {{- range $key, $val := .Values.ingress.annotations }}
    {{- if $val }}
    {{ $key }}: {{ $val }}
    {{- end }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.global.app_url }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-bookstack
                port:
                  name: web
            path: /
            pathType: Prefix
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.global.app_url }}
      secretName: {{ .Release.Name }}-bookstack-ssl
  {{- end }}
