---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-bookstack-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
data:
  PUID: {{ .Values.puid | quote }}
  PGID: {{ .Values.pgid | quote }}
  APP_URL: "https://{{ .Values.global.app_url }}"
  {{- if .Values.mariadb.enabled }}
  DB_HOST: {{ template "mariadb.primary.fullname" .Subcharts.mariadb }}
  {{- else }}
  DB_HOST: {{ .Values.mariadb.host | quote }}
  {{- end }}
  DB_USER: {{ .Values.mariadb.auth.username | quote }}
  DB_PASS: {{ .Values.mariadb.auth.password | quote }}
  DB_DATABASE: {{ .Values.mariadb.auth.database | quote }}
  {{- if .Values.mail.enabled }}
  MAIL_DRIVER: {{ .Values.mail.driver | quote }}
  MAIL_HOST: {{ .Values.mail.host | quote }}
  MAIL_PORT: {{ .Values.mail.port | quote }}
  MAIL_ENCRYPTION: {{ .Values.mail.encryption | quote }}
  MAIL_USERNAME: {{ .Values.mail.username | quote }}
  MAIL_PASSWORD: {{ .Values.mail.password | quote }}
  MAIL_FROM: {{ .Values.mail.from | quote }}
  MAIL_FROM_NAME: {{ .Values.mail.from_name | quote }}
  {{- end }}
  {{- if .Values.auth.azure.enabled }}
  AZURE_APP_ID: {{ .Values.auth.azure.app_id | quote }}
  AZURE_APP_SECRET: {{ .Values.auth.azure.app_secret | quote }}
  AZURE_TENANT: {{ .Values.auth.azure.tenant | quote }}
  AZURE_AUTO_REGISTER: {{ .Values.auth.azure.auto_register | quote }}
  AZURE_AUTO_CONFIRM_EMAIL: {{ .Values.auth.azure.auto_confirm | quote }}
  {{- end }}
