---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mariadb-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: mariadb
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.rootpass | quote }}
  MYSQL_DATABASE: {{ .Values.db.name | quote }}
  MYSQL_USER: {{ .Values.db.user | quote }}
  MYSQL_PASSWORD: {{ .Values.db.pass | quote }}

---        
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/name: mariadb
spec:
  serviceName: {{ .Release.Name }}-mariadb
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
      app.kubernetes.io/name: mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ .Release.Name }}
        app.kubernetes.io/name: mariadb
    spec:
      containers:
      - name: {{ .Release.Name }}-mariadb
        image: "{{ .Values.db.image.name }}:{{ .Values.db.image.tag }}"
        volumeMounts:
        - name: {{ .Release.Name }}-mariadb
          mountPath: /var/lib/mysql
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-mariadb-env
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-mariadb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.global.storageclass | quote }}
      resources:
        requests:
          storage: {{ .Values.db.size | quote }}
