{{- if not .Values.mariadb.host }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-mariadb-env
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mariadb
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.mariadb.rootpass | quote }}
  MYSQL_DATABASE: {{ .Values.mariadb.name | quote }}
  MYSQL_USER: {{ .Values.mariadb.user | quote }}
  MYSQL_PASSWORD: {{ .Values.mariadb.pass | quote }}

---        
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mariadb
spec:
  serviceName: {{ .Release.Name }}-mariadb
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Release.Name }}
      app.kubernetes.io/component: database
      app.kubernetes.io/name: mariadb
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: database
        app.kubernetes.io/name: mariadb
    spec:
      containers:
      - name: {{ .Release.Name }}-mariadb
        image: "{{ .Values.mariadb.image.name }}:{{ .Values.mariadb.image.tag }}"
        ports:
          - containerPort: 3306
            name: mysql
            protocol: TCP
        volumeMounts:
        - name: {{ .Release.Name }}-mariadb
          mountPath: /var/lib/mysql
        envFrom:
        - configMapRef:
            name: {{ .Release.Name }}-mariadb-env
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-mariadb
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: {{ .Values.global.storageclass | quote }}
      resources:
        requests:
          storage: {{ .Values.mariadb.storage.size | quote }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-mariadb
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mariadb
spec:
  ports:
    - name: mysql
      port: 3306
      protocol: TCP
      targetPort: mysql
  selector:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: database
    app.kubernetes.io/name: mariadb
  type: ClusterIP
{{- end }}