---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bookstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Release.Name }}
      app.kubernetes.io/component: application
      app.kubernetes.io/name: bookstack
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: application
        app.kubernetes.io/name: bookstack
    spec:
      containers:
        - name: {{ .Release.Name }}-bookstack
          image: "{{ .Values.bookstack.image.name }}:{{ .Values.bookstack.image.tag }}"
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-bookstack
              mountPath: /config
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-bookstack-env
      volumes:
        - name: {{ .Release.Name }}-bookstack
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-bookstack
