---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-bookstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.bookstack.storage.size }}
  storageClassName: {{ .Values.global.storageclass | quote }}
