---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-bookstack
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: bookstack
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: 80
