global:
  storageclass: ""
  app_url: ""

joplin:
  image:
    name: "joplin/server"
    tag: "2.7.4-beta"
  storage:
    size: "5Gi"
  port: "22300"

postgres:
  host: "" # Leave empty to make it spin up its own database.
  name: "joplin"
  user: "joplin"
  pass: "changeit!"
  port: "5432"
  image:
    name: "postgres"
    tag: "13.1"
  storage:
    size: "5Gi"

mail:
  enabled: false
  driver: "smtp"
  host: "smtp.provider.tld"
  port: "465"
  encryption: "tls"
  username: "user@provider.tld"
  password: "onlyifneeded"
  from: "noreply@yourdomain.tld"
  from_name: "BookStack"

ingress:
  tls: false
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "cert-manager.io/cluster-issuer": ""