global:
  storageClass: ""
  app_url: "joplin.local"
  postgresql:
    auth:
      username: joplin
      password: changeIt!
      database: joplin
      postgresPassword: changeIt!
    service:
      ports:
        postgresql: 5432

joplin:
  image:
    name: "joplin/server"
    tag: "2.7.4-beta"
  storage:
    size: "5Gi"
  port: "22300"

postgresql:
  enabled: "yes" # Change to yes if you have another DB running.
  host: "" # Define the DB host, leave empty when using template DB.

mail:
  enabled: false
  host: "smtp.provider.tld"
  port: "465"
  encryption: "tls"
  username: "user@provider.tld"
  password: "onlyifneeded"
  from: "noreply@yourdomain.tld"
  from_name: "Joplin"

ingress:
  enabled: false
  tls: false
  annotations:
    "kubernetes.io/ingress.class": "nginx"
    "cert-manager.io/cluster-issuer": ""