global:
  storageclass: ""
  app_url: ""

image:
  name: "linuxserver/bookstack"
  tag: "22.03.1"

storage:
  size: "5Gi"

puid: "1000"
pgid: "1000"

mariadb:
  enabled: "yes" # Change to yes if you have another DB running.
  host: "" # Define the DB host, leave empty when using template DB.
  auth:
    database: "bookstack"
    rootPassword: "changeit!"
    username: "bookstack"
    password: "changeit!"

mail:
  enabled: false
  driver: "smtp"
  host: "smtp.provider.tld"
  port: "465"
  encryption: "tls"
  username: "user@provider.tld"
  password: "onlyifneeded"
  from: "noreply@yourdomain.tld"
  from_name: "BookStack"

auth:
  azure:
    enabled: false
    app_id: ""
    app_secret: ""
    tenant: ""
    auto_register: false
    auto_confirm: false

ingress:
  tls: false
  annotations:
    "kubernetes.io/ingress.class": ""
    "cert-manager.io/cluster-issuer": ""