global:
  storageclass: ""
  app_url: ""

bookstack:
  image:
    name: "linuxserver/bookstack"
    tag: "22.03.1"
  storage:
    size: "5Gi"
  puid: "1000"
  pgid: "1000"

mariadb:
  host: "" # Leave empty to make it spin up its own database.
  name: "bookstack"
  user: "bookstack"
  pass: "changeit!"
  image:
    name: "mariadb"
    tag: 10
  rootpass: "changeme!"
  storage:
    size: "5Gi"

ingress:
  tls: false
  annotations:
    kubernetes.io/ingress.class: ""
    cert-manager.io/cluster-issuer: ""