---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-joplin
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: joplin
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Release.Name }}
      app.kubernetes.io/component: application
      app.kubernetes.io/name: joplin
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: application
        app.kubernetes.io/name: joplin
    spec:
      containers:
        - name: {{ .Release.Name }}-joplin
          image: "{{ .Values.joplin.image.name }}:{{ .Values.joplin.image.tag }}"
          ports:
            - containerPort: {{ .Values.joplin.port | int }}
              name: web
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-joplin
              mountPath: /config
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-joplin-env
      volumes:
        - name: {{ .Release.Name }}-joplin
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-joplin