---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vansxml
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: vansxml
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Release.Name }}
      app.kubernetes.io/component: application
      app.kubernetes.io/name: vansxml
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: application
        app.kubernetes.io/name: vansxml
    spec:
      containers:
        - name: {{ .Release.Name }}-vansxml
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8228
              name: web
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "/"
              port: 8228
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: "/"
              port: 8228
              scheme: HTTP
          volumeMounts:
            name: db
            mountPath: "/src/db"
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-vansxml"