{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-vansxml
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: vansxml
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.global.app_url }}
      http:
        paths:
          - backend:
              service:
                name: {{ .Release.Name }}-vansxml
                port:
                  name: web
            path: /
            pathType: Prefix
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.global.app_url }}
      secretName: {{ .Release.Name }}-vansxml-ssl
  {{- end }}
{{- end -}}