global:
  storageClass: ""
  app_url: "umami.local"

image:
  name: "joene/form2xml"
  tag: "edge"

storage:
  size: 5Gi

postgresql:
  enabled: true # Change to false if you have another DB running.
  host: "" # Define the DB host when postgresql.enabled is false.
  primary:
    initdb:
      scriptsConfigMap: "{{ .Release.Name }}-umami-sql"

ingress:
  enabled: false
  tls: false
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: ""