---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: traccar
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Release.Name }}
      app.kubernetes.io/component: application
      app.kubernetes.io/name: traccar
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: application
        app.kubernetes.io/name: traccar
    spec:
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8082
              name: web
              protocol: TCP
            {{- range .Values.dataports }}
            - containerPort: {{ .port | toString }}
              name: "data-{{ .port | toString }}"
              protocol: TCP
            {{- end  }}
          volumeMounts:
            - name: data
              mountPath: /opt/traccar/data
            - name: logs
              mountPath: /opt/traccar/logs
            - name: config
              mountPath: /opt/traccar/conf/traccar.xml
              subPath: traccar.xml
      volumes:
        - name: 'data'
          persistentVolumeClaim:
            claimName: "{{ .Release.Name }}-data"
        - name: 'logs'
          persistentVolumeClaim: 
            claimName: "{{ .Release.Name }}-logs"
        - name: 'config'
          configMap:
            name: "{{ .Release.Name }}-config"