---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: traccar
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: traccar
  ports:
    - name: web
      port: 8082
      protocol: TCP
      targetPort: 8082

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-data
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: traccar
spec:
  type: NodePort
  selector:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: traccar
  ports:
    - name: web
      port: 8082
      protocol: TCP
      targetPort: 8082
    {{- range .Values.dataports }}
    - port: {{ .port }}
      name: "data-{{ .port }}"
      nodePort: {{ .externalPort }}
    {{- end  }}