---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-shynet
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: shynet
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Release.Name }}
      app.kubernetes.io/component: application
      app.kubernetes.io/name: shynet
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: application
        app.kubernetes.io/name: shynet
    spec:
      containers:
        - name: {{ .Release.Name }}-shynet
          image: "{{ .Values.shynet.image.name }}:{{ .Values.shynet.image.tag }}"
          ports:
            - containerPort: {{ .Values.shynet.port | int }}
              name: web
              protocol: TCP
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}-shynet-env
          livenessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.shynet.port | int }}
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /healthz
              port: {{ .Values.shynet.port | int }}
            initialDelaySeconds: 3
            periodSeconds: 3