---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-shynet
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: shynet
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: shynet
  ports:
    - name: web
      port: 80
      protocol: TCP
      targetPort: {{ .Values.shynet.port | int }}