---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-checkmk
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: checkmk
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: {{ .Release.Name }}
      app.kubernetes.io/component: application
      app.kubernetes.io/name: checkmk
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: {{ .Release.Name }}
        app.kubernetes.io/component: application
        app.kubernetes.io/name: checkmk
    spec:
      containers:
        - name: {{ .Release.Name }}-checkmk
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 5000
              name: web
              protocol: TCP
          volumeMounts:
            - name: {{ .Release.Name }}-checkmk
              mountPath: /omd/sites
          livenessProbe:
            httpGet:
              path: "/"
              port: 5000
              scheme: HTTP
          readinessProbe:
            httpGet:
              path: "/"
              port: 5000
              scheme: HTTP
      volumes:
        - name: {{ .Release.Name }}-checkmk
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-checkmk