apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-checkmk
  namespace: {{ .Release.Namespace }}
type: Opaque
data:
  CMK_SITE_ID: {{ .Values.config.site_id | b64enc }}
  CMK_PASSWORD: {{ .Values.config.password | b64enc }}