---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-checkmk
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: checkmk
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/part-of: {{ .Release.Name }}
    app.kubernetes.io/component: application
    app.kubernetes.io/name: checkmk
  ports:
    - name: web
      port: 5000
      protocol: TCP